[package]
name = "colorize"
version = "0.5.0"
edition = "2021"
description = "A set of Rust macros to assist in turning text into colors for printing on the terminal."
readme = "README.md"
repository = "https://github.com/jpal91/colorize"
license = "MIT"
keywords = ["ansi", "color", "macros"]
categories = ["command-line-interface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
