workspace = { members = ["proc-colorize"] }
[package]
name = "colorize-macros"
version = "0.8.0"
edition = "2021"
description = "A set of Rust macros to assist in turning text into colors for printing on the terminal."
readme = "README.md"
repository = "https://github.com/jpal91/colorize"
license = "MIT"
keywords = ["ansi", "color", "macros"]
categories = ["command-line-interface"]
exclude = [".github/**", "assets/**"]

[lib]
name = "colorize"
path = "src/lib.rs"


[dependencies]
colorize-proc-macro = { version = "^0.2.0", path = "proc-colorize" }

